### ISSUE TITLE
Hi! I have questions regarding the visualization feature.

### ISSUE THREAD

**Issue by umamicode** [snimu/rebasin#14]
Thanks for the amazing project, I have an inquiry regarding the visualization feature mentioned in the tutorial.
What does this mean? Can you elaborate a little further please?

Thanks!

*************

print(pcd.pinit.model_graph) returns an output like this:
--------------------------------------------------------------------------------------------
ParallelPaths(                                                                              
  LinearPath(                                  LinearPath(                                  
    DefaultModule(                               DefaultModule(                             
      module.type: Conv2d                          module.type: Conv2d                      
      input.shape: [(128, 64, 56, 56)]             input.shape: [(128, 64, 56, 56)]         
      output.shape: [(128, 64, 56, 56)]            output.shape: [(128, 256, 56, 56)]       
      weight.in_dim.permutation: None              weight.in_dim.permutation: None          
      weight.out_dim.permutation.shape: 64         weight.out_dim.permutation.shape: 256    
    )                                            )                                          
                                                                                            
    OneDimModule(                                OneDimModule(                              
      module.type: BatchNorm2d                     module.type: BatchNorm2d                 
      input.shape: [(128, 64, 56, 56)]             input.shape: [(128, 256, 56, 56)]        
      output.shape: [(128, 64, 56, 56)]            output.shape: [(128, 256, 56, 56)]       
      weight.in_dim.permutation.shape: 64          weight.in_dim.permutation.shape: 256     
      weight.out_dim.permutation.shape: 64         weight.out_dim.permutation.shape: 256    
    )                                            )                                          
                                                                                            
    DefaultModule(                             )                                            
      module.type: Conv2d                                         |                         
      input.shape: [(128, 64, 56, 56)]                            |                         
      output.shape: [(128, 64, 56, 56)]                           |                         
      weight.in_dim.permutation.shape: 64                         |                         
      weight.out_dim.permutation.shape: 64                        |                         
    )                                                             |                         
                                                                  |                         
    OneDimModule(                                                 |                         
      module.type: BatchNorm2d                                    |                         
      input.shape: [(128, 64, 56, 56)]                            |                         
      output.shape: [(128, 64, 56, 56)]                           |                         
      weight.in_dim.permutation.shape: 64                         |                         
      weight.out_dim.permutation.shape: 64                        |                         
    )                                                             |                         
                                                                  |                         
    DefaultModule(                                                |                         
      module.type: Conv2d                                         |                         
      input.shape: [(128, 64, 56, 56)]                            |                         
      output.shape: [(128, 256, 56, 56)]                          |                         
      weight.in_dim.permutation.shape: 64                         |                         
      weight.out_dim.permutation.shape: 256                       |                         
    )                                                             |                         
                                                                  |                         
    OneDimModule(                                                 |                         
      module.type: BatchNorm2d                                    |                         
      input.shape: [(128, 256, 56, 56)]                           |                         
      output.shape: [(128, 256, 56, 56)]                          |                         
      weight.in_dim.permutation.shape: 256                        |                         
      weight.out_dim.permutation.shape: 256                       |                         
    )                                                             |                         
                                                                  |                         
  )                                                               |                         
)                                                                                           
--------------------------------------------------------------------------------------------

 (please refer to attached txt file for full result):

[vis.txt](https://github.com/snimu/rebasin/files/12879073/vis.txt)

**Comment by snimu** [comment]
Hi, thanks for your interest! This output is meant mostly for debugging the permutations. The main difficulty in this package is that parameters of subsequent modules share the same permutation, but only if their shapes fit and only if the permutation doesn't change the output. Choosing which parameters share the same permutation in arbitrary model architectures is challenging, and the ability to print the permutation graph has helped me in debugging.
The modules that you see are called that way because I group different torch modules into different classes, because they have to be treated differently. 
The module type is the torch module to which the parameter belongs.
The input shape and output shape are the shapes of the tensor at the input and output of that module.
Finally, the weight.in_dim... and out_dim... shapes are the shapes of the permutations themselves. This is because each permutation matrix is represented by two vectors, one for the input dimension (eg dimension 1 in a linear layer's weight tensor) and one for the output dimension (eg dim 0 in a linear layer). 

The modules (like the DefaultModule, etc.) appear in the order that the corresponding modules of the model are called. If some modules are called in parallel, that is indicated as well. 

I hope that this helps; if you have more questions, feel free to ask :)

**Comment by umamicode** [comment]
Thank you again for the work!
